---
version: "2"
checks:
  identical-code:
    enabled: false
  similar-code:
    enabled: false
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          count_threshold: 3
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
    config: 
      file: .rubocop.yml
exclude_patterns:
- config/
- db/
- features/
- script/
- spec/
- vendor/
- public/
