source 'https://rubygems.org'

ruby '3.0.0'

gem 'rails', '~> 6.0'
gem 'acts-as-taggable-on'
gem 'acts_as_follower', git: 'https://github.com/AgileVentures/acts_as_follower.git'
gem 'acts_as_tree'
gem 'acts_as_votable', '~> 0.12.1'
gem 'airbrake'
# gem 'apipie-rails'
gem 'addressable'
gem 'bootstrap-sass'
gem 'cocoon'
gem 'code_climate_badges', git: 'https://github.com/AgileVentures/codeclimate_badges'
gem 'coderay'
gem 'coffee-rails'
gem 'colored'
gem 'compass-rails', '~> 4.0'
gem 'config'
gem 'devise', '~> 4.7'
gem 'eventmachine', '~> 1.2.7'
gem 'exception_notification'
gem 'factory_bot_rails'
gem 'faker'
gem 'font-awesome-rails'
gem 'friendly_id'
gem 'geocoder'
gem 'grape'
gem 'ice_cube', '0.16.3'
gem 'jbuilder'
gem 'jquery-rails'
gem 'jquery-turbolinks', '2.1.0'
gem 'jvectormap-rails', '~> 2.0'
gem 'jwt'
gem 'kaminari'
gem 'kramdown', '~> 2.1'
gem 'letter_opener', :group => :development
gem 'local_time', '~> 2.1'
gem 'mercury-rails', git: 'https://github.com/AgileVentures/mercury.git'
gem 'nokogiri', '1.11.5'
gem 'octokit'
gem 'omniauth'
gem 'omniauth-github'
gem 'omniauth-oauth2'
gem 'omniauth-google-oauth2'
gem 'omniauth-rails_csrf_protection'
gem 'paper_trail', '~> 12.0'
gem 'paranoia', '~> 2.4'
gem 'paypal-sdk-rest'
gem 'pg'
gem 'pivotal-tracker-api', git: 'https://github.com/AgileVentures/pivotal-tracker-api.git'
gem 'public_activity'
gem 'puma'
gem 'rack-cache'
gem 'rack-cors', :require => 'rack/cors'
gem 'rails_autolink', '~>1.1.6'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'redcarpet'
gem 'ruby-gitter'
gem 'sass-rails', '~> 5.0', '>= 5.0.8'
gem 'simple_form', '~> 5.0'
gem 'slack-ruby-client'
gem 'spinjs-rails'
gem 'sprockets-rails', '~> 3.2', '>= 3.2.1'
gem 'stripe'
gem 'sucker_punch'
# gem 'therubyracer', platforms: :ruby
gem 'turbolinks'
gem 'uglifier'
gem 'utf8-cleaner'
gem 'vanity'
gem 'verbs'
gem 'will_paginate-bootstrap'
gem 'yt'
gem 'youtube_rails'
gem 'bootsnap', '~> 1.4'
gem 'icalendar'
gem 'seed_dump'
gem 'mime-types', '~> 3.3', '>= 3.3.1'
gem 'sorted_set', '~> 1.0', '>= 1.0.3'

group :test do
  gem 'capybara'
  gem 'capybara-selenium', '~> 0.0.6'
  gem 'capybara-screenshot'
  gem 'cucumber-rails', '~> 2.0', require: false
  gem 'database_cleaner'
  gem 'delorean' # gem is discontinued
  gem 'launchy'
  gem 'phantomjs', require: 'phantomjs/poltergeist' # not maintained since 2016
  gem 'poltergeist' # not maintained since 2018
  gem 'puffing-billy', '~> 2.2.0'
  gem 'rails-controller-testing', '~> 1.0', '>= 1.0.2'
  gem 'rubocop-performance', '~> 1.5', '>= 1.5.2'
  gem 'rubocop-rails', '~> 2.5', '>= 2.5.2'
  gem 'rubocop-rspec', '>=1.28'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers', require: false
  gem 'stripe-ruby-mock', '~> 3.1.0.rc2', require: 'stripe_mock'
  gem 'vcr'
  gem 'webmock'
end

group :development do
  gem 'better_errors'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'awesome_print'
  gem 'binding_of_caller'
  gem 'brakeman', require: false
  gem 'bullet'
  gem 'bundler-audit', require: false
  gem 'constant-redefinition'
  gem 'dotenv-rails'
  gem 'rails-erd'
  gem 'guard'
  gem 'guard-cucumber'
  gem 'guard-livereload'
  gem 'guard-rspec'
  gem 'hirb'
  gem 'jasmine', '~> 3.5'
  gem 'jasmine-jquery-rails', '~> 2.0', '>= 2.0.3'
  gem 'pry-rails'
  gem 'railroady'
  gem 'rb-readline'
  gem 'rspec-activemodel-mocks'
  gem 'rspec-html-matchers'
  gem 'simplecov', '~> 0.17.1'
  gem 'coveralls', require: false
end

group :staging, :production do
  gem 'rack-timeout'
end

group :production do
  gem 'newrelic_rpm'
end
