source 'https://rubygems.org'
ruby '2.3.1'

gem 'rails', '4.2.8'
gem 'active_model-errors_details'
gem 'acts-as-taggable-on'
gem 'acts_as_follower'
gem 'acts_as_tree'
gem 'acts_as_votable', '~> 0.10.0'
gem 'addressable'
gem 'bootstrap-sass'
gem 'cocoon'
gem 'code_climate_badges', git: 'https://github.com/AgileVentures/codeclimate_badges'
gem 'coderay'
gem 'coffee-rails'
gem 'colored'
gem 'compass-rails'
gem 'config'
gem 'devise', '~> 3.5.1'
gem 'eventmachine', '~> 1.0.7'
gem 'exception_notification'
gem 'factory_girl_rails', '4.5.0'
gem 'faker'
gem 'font-awesome-rails'
gem 'friendly_id'
gem 'geocoder'
gem 'ice_cube', '0.11.1'
gem 'jbuilder'
gem 'jquery-rails'
gem 'jquery-turbolinks', '2.0.2'
gem 'jvectormap-rails', '~> 1.0.0'
gem 'kaminari'
gem 'local_time', '~> 1.0.3'
gem 'mercury-rails', git: 'https://github.com/jejacks0n/mercury.git'
gem 'nearest_time_zone'
gem 'nokogiri', '1.7.2'
gem 'octokit'
gem 'omniauth'
gem 'omniauth-github', '~> 1.1.2'
gem 'omniauth-gplus', '~> 2.0.1'
gem 'omniauth-oauth2', '~> 1.3.1'
gem 'paper_trail', '4.0.0'
gem 'paranoia', '~> 2.2'
gem 'pg'
gem 'pivotal-tracker-api', '0.1.9'
gem 'polyamorous', '~> 1.2.0'
gem 'public_activity'
gem 'puma'
gem 'rack-cache'
gem 'rails_autolink', '~>1.1.6'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'redcarpet'
gem 'ruby-gitter'
gem 'sass-rails'
gem 'slack-ruby-client'
gem 'sprockets-rails', '2.3.3'
gem 'stripe'
gem 'sucker_punch'
gem 'therubyracer', platforms: :ruby
gem 'turbolinks'
gem 'twitter', '~> 5.11.0'
gem 'uglifier'
gem 'utf8-cleaner'
gem 'verbs'
gem 'will_paginate-bootstrap'
gem 'yt'
gem 'yui-compressor'
gem 'youtube_rails'

group :test do
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'capybara-screenshot'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem 'delorean'
  gem 'launchy'
  gem 'phantomjs', require: 'phantomjs/poltergeist'
  gem 'poltergeist'
  gem 'puffing-billy'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers', require: false
  gem 'stripe-ruby-mock', '~> 2.3.1', require: 'stripe_mock'
  gem 'vcr'
  gem 'webmock'
  gem 'webrat'
  gem 'zeus'
end

group :development, :test do
  gem 'awesome_print'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'brakeman', require: false
  gem 'bullet'
  gem 'bundler-audit', require: false
  gem 'constant-redefinition'
  gem 'dotenv-rails'
  gem 'guard'
  gem 'guard-cucumber'
  gem 'guard-livereload'
  gem 'guard-rspec'
  gem 'hirb'
  gem 'jasmine'
  gem 'jasmine-jquery-rails'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'railroady'
  gem 'rspec'
  gem 'rspec-activemodel-mocks'
  gem 'rspec-html-matchers'
  gem 'rspec-rails'
  gem 'coveralls', require: false
  gem 'simplecov'
end

group :development, :staging, :production do
  gem 'rack-timeout'
end

group :production do
  gem 'airbrake'
  gem 'newrelic_rpm'
  gem 'rails_12factor'
end
