#@event = mock_model(Event, name: 'one time event',
#                    description: '',
#                    is_all_day: false,
#                    from_date: 'Mon, 17 Jun 2013',
#                    from_time: '2000-01-01 09:00:00 UTC',
#                    to_date: 'Mon, 17 Jun 2013',
#                    to_time: '2000-01-01 17:00:00 UTC',
#                    repeats: 'never',
#                    repeats_every_n_days: nil,
#                    repeats_every_n_weeks: nil,
#                    repeats_every_n_months: nil,
#                    repeats_monthly: 'each',
#                    repeats_every_n_years: nil,
#                    repeats_yearly_on: false,
#                    repeat_ends: 'never',
#                    repeat_ends_on: 'Mon, 17 Jun 2013',
#                    time_zone: 'Eastern Time (US & Canada)')
