features:
  custom_errors:
    enabled: false
  slack:
    notifications:
      enabled: false
    invites:
      enabled: false
  welcome_email:
    enabled: false

hangouts:
  app_id: '10095526298'
# comma separated list
privileged_users: "random@random.com"
