require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NewslettersController do

  # This should return the minimal set of attributes required to create a valid
  # Newsletter. As you add validations to Newsletter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { FactoryGirl.attributes_for(:newsletter) }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NewslettersController. Be sure to keep this updated too.
  let(:valid_session) { {} }
  let(:user) { @user }

  

  describe "As privilged user" do

    before :each do
      @user = get_privileged_user
      request.env['warden'].stub :authenticate => @user
      controller.stub :current_user =>  @user
    end

    describe "GET index" do
      it "assigns all newsletters as @newsletters" do
        newsletter = FactoryGirl.create(:newsletter) 
        get :index, {}, valid_session
        assigns(:newsletters).should eq([newsletter])
      end
    end

    describe "GET show" do
      it "assigns the requested newsletter as @newsletter" do
        newsletter = FactoryGirl.create(:newsletter)
        get :show, {:id => newsletter.to_param}, valid_session
        assigns(:newsletter).should eq(newsletter)
      end
    end

    describe "GET new" do
      it "assigns a new newsletter as @newsletter" do
        get :new, {}, valid_session
        assigns(:newsletter).should be_a_new(Newsletter)
      end
    end

    describe "GET edit" do
      it "assigns the requested newsletter as @newsletter" do
        newsletter = FactoryGirl.create(:newsletter) 
        get :edit, {:id => newsletter.to_param}, valid_session
        assigns(:newsletter).should eq(newsletter)
      end
    end

    describe "POST create" do
      describe "with valid params" do
        it "creates a new Newsletter" do
          expect {
            post :create, {:newsletter => valid_attributes}, valid_session
          }.to change(Newsletter, :count).by(1)
        end

        it "assigns a newly created newsletter as @newsletter" do
          post :create, {:newsletter => valid_attributes}, valid_session
          assigns(:newsletter).should be_a(Newsletter)
          assigns(:newsletter).should be_persisted
        end

        it "redirects to the created newsletter" do
          post :create, {:newsletter => valid_attributes}, valid_session
          response.should redirect_to(Newsletter.last)
        end
      end

      describe "with invalid params" do
        it "assigns a newly created but unsaved newsletter as @newsletter" do
          # Trigger the behavior that occurs when invalid params are submitted
          Newsletter.any_instance.stub(:save).and_return(false)
          post :create, {:newsletter => { "title" => "invalid value" }}, valid_session
          assigns(:newsletter).should be_a_new(Newsletter)
        end

        it "re-renders the 'new' template" do
          # Trigger the behavior that occurs when invalid params are submitted
          Newsletter.any_instance.stub(:save).and_return(false)
          post :create, {:newsletter => { "title" => "invalid value" }}, valid_session
          response.should render_template("new")
        end
      end
    end

    describe "PUT update" do
      describe "with valid params" do
        it "updates the requested newsletter" do
          newsletter = FactoryGirl.create(:newsletter) 
          # Assuming there are no other newsletters in the database, this
          # specifies that the Newsletter created on the previous line
          #  receives the :update_attributes message with whatever params are
          # submitted in the request.
          Newsletter.any_instance.should_receive(:update).with({ "title" => "MyString" })
          put :update, {:id => newsletter.to_param, :newsletter => { "title" => "MyString" }}, valid_session
        end

        it "assigns the requested newsletter as @newsletter" do
          newsletter = FactoryGirl.create(:newsletter) 
          put :update, {:id => newsletter.to_param, :newsletter => valid_attributes}, valid_session
          assigns(:newsletter).should eq(newsletter)
        end

        it "redirects to the newsletter" do
          newsletter = FactoryGirl.create(:newsletter) 
          put :update, {:id => newsletter.to_param, :newsletter => valid_attributes}, valid_session
          response.should redirect_to(newsletter)
        end
      end

      describe "with invalid params" do
        it "assigns the newsletter as @newsletter" do
          newsletter = FactoryGirl.create(:newsletter) 
          # Trigger the behavior that occurs when invalid params are submitted
          Newsletter.any_instance.stub(:save).and_return(false)
          put :update, {:id => newsletter.to_param, :newsletter => { "title" => "invalid value" }}, valid_session
          assigns(:newsletter).should eq(newsletter)
        end

        it "re-renders the 'edit' template" do
          newsletter = FactoryGirl.create(:newsletter) 
          # Trigger the behavior that occurs when invalid params are submitted
          Newsletter.any_instance.stub(:save).and_return(false)
          put :update, {:id => newsletter.to_param, :newsletter => { "title" => "invalid value" }}, valid_session
          response.should render_template("edit")
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested newsletter" do
        newsletter = FactoryGirl.create(:newsletter) 
        expect {
          delete :destroy, {:id => newsletter.to_param}, valid_session
        }.to change(Newsletter, :count).by(-1)
      end

      it "redirects to the newsletters list" do
        newsletter = FactoryGirl.create(:newsletter) 
        delete :destroy, {:id => newsletter.to_param}, valid_session
        response.should redirect_to(newsletters_url( only_path: true))
      end
    end

  end

  describe "As unpvivileged user" do
    
    before :each do
      @user =  FactoryGirl.create(:user)
      request.env['warden'].stub :authenticate => @user
      controller.stub :current_user =>  @user
    end
    
    describe "GET new" do
      it "renders status 403" do
        get :new, {}, valid_session
        expect(response.status).to eq(403)
      end
    end

    describe "GET edit" do
      it "renders status 403" do
        newsletter = FactoryGirl.create(:newsletter) 
        get :edit, {:id => newsletter.to_param}, valid_session
        expect(response.status).to eq(403)
      end
    end
    
    describe "DELETE destroy" do
      it "wont delete Newsletter" do
        newsletter = FactoryGirl.create(:newsletter) 
        expect {
          delete :destroy, {:id => newsletter.to_param}, valid_session
        }.to change(Newsletter, :count).by(0)
        expect(response.status).to eq(403)
      end
      
      it "renders status 403" do
        newsletter = FactoryGirl.create(:newsletter) 
        delete :destroy, {:id => newsletter.to_param}, valid_session
        expect(response.status).to eq(403)
      end
    end

    describe "PUT update" do
      it "renders status 403" do
        newsletter = FactoryGirl.create(:newsletter) 
        put :update, {:id => newsletter.to_param, :newsletter => { "title" => "MyString" }}, valid_session
        expect(response.status).to eq(403)
      end

      it "displays template 403" do
        newsletter = FactoryGirl.create(:newsletter) 
        put :update, {:id => newsletter.to_param, :newsletter => { "title" => "MyString" }}, valid_session
        expect(response).to  render_template(:file => "#{Rails.root}/public/403.html") 
      end
    end
  end

end
